<?xml version="1.0" encoding="utf-8"?><Database Name="spaceTravel" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=cd-dt-sql.clients.nasa.cpwr.corp;Initial Catalog=spaceTravel;Persist Security Info=True;User ID=dt" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="spaceTravelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.potus" Member="potus">
    <Type Name="potus">
      <Column Name="president_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="president_name_common" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="president_name_birth" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="president_number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="president_term_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="president_term_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.revenue" Member="revenues">
    <Type Name="revenue">
      <Column Name="revenue_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="revenue_desc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="revenue_amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="revenue_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RTBTF" Member="RTBTFs">
    <Type Name="RTBTF">
      <Column Name="rtbtf_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rtbtf_raw" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="rtbtf_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[dynatrace-category]" Member="dynatrace_categories">
    <Type Name="dynatrace_category">
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="category_name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="category_description" Type="System.String" DbType="VarChar(5000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.link" Member="links">
    <Type Name="link">
      <Column Name="link_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="link_name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="link_url" Type="System.String" DbType="VarChar(5000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>