(function() {
var f=!0,k=null,l=!1;function m(){return(new Date).getTime()}var aa=m(),n=window,p=n.setTimeout,ba=n.XMLHttpRequest,ca=n.ActiveXObject,r=n.parent,s={version:"5802"};"undefined"==typeof n.dT_&&(document.dT_=window.dT_,n.dT_=s);function da(){return ba?new ba:new ca("MSXML2.XMLHTTP.3.0")}
function t(a){var b,c,d,e=document.cookie.split(";");for(b=0;b<e.length;b++)if(c=e[b].indexOf("\x3d"),d=e[b].substring(0,c),c=e[b].substring(c+1),d=d.replace(/^\s+|\s+$/g,""),d==a)return"DTSA"==a.toUpperCase()?decodeURIComponent(c):c;return k}function u(a,b){b?(b="DTSA"==a.toUpperCase()?v(b):b,document.cookie=a+"\x3d"+b+";path\x3d/"+(w.domain?";domain\x3d"+w.domain:"")):document.cookie=a+'\x3d"";path\x3d/'+(w.domain?";domain\x3d"+w.domain:"")+"; expires\x3dThu, 01-Jan-70 00:00:01 GMT;"}
function x(a,b){for(var c=1;c<arguments.length;c++)a.push(arguments[c])}s.sC=u;s.gC=t;s.gx=da;s.st=function(a,b){return p(a,b)};s.nw=m;var y=[],z=navigator.userAgent;
try{var ea=/Firefox[\/\s](\d+\.\d+)/,fa=/(iPod|iPhone|iPad)/,ga=/AppleWebKit/;if(0<=z.indexOf("MSIE"))y.ie=~~z.substr(z.lastIndexOf("MSIE")+5,3);else if(0<=z.indexOf("Trident"))0<=z.indexOf("rv:")?y.ie=~~z.substr(z.lastIndexOf("rv:")+3,2):0<=z.indexOf("rv ")&&(y.ie=~~z.substr(z.lastIndexOf("rv ")+3,2));else if(0<=z.indexOf("Android"))y.ab=parseFloat(z.substr(z.indexOf("Android")+8,1));else if(z.match(fa)&&z.match(ga))y.msf=parseFloat(z.match(/Version\/([0-9]*\.[0-9]*)/)[1]);else if(("Safari"==navigator.appName||
-1<z.indexOf("Safari"))&&-1==z.indexOf("Chrom"))y.sf=~~z.substr(z.lastIndexOf("Version/")+8,1);else if(n.opera)y.op=~~n.opera.version().split(".")[0];else if(ea.test(z)){var ha=~~z.match(ea)[1];y.ff=-1==ha?0:ha}else{var ia=z.indexOf("Chrom");-1<ia&&(y.ch=~~z.substring(ia+7,ia+9))}}catch(ja){}s.gBI=function(){return y};var w={reportUrl:"dynaTraceMonitor",m:""};function ka(a){return!a||1!=a.length||void 0===w.t?l:-1!=w.t.indexOf(a)}var la=document.getElementsByTagName("script");
if(0<la.length)for(var ma,na=la.length-1;0<=na;na--)if(ma=la[na],0<=ma.src.search("dtagent")&&ma.attributes){var oa=ma.attributes.getNamedItem("data-dtconfig");if(oa&&oa.value){var pa=ma.src,qa=oa.value;if(pa){var ra=/dtagent(dbg){0,1}[0-9]{2}_[a-zA-Z_0-9]*_[0-9]{4}/.exec(pa);ra&&(w.t=ra[0].split("_")[1])}if(qa)for(var A=qa.split("|"),B=0;B<A.length;B++){var sa=A[B].indexOf("\x3d");-1==sa?w[A[B]]=f:w[A[B].substring(0,sa)]=A[B].substring(sa+1,A[B].length)}}break}
s.smbi=function(a){if(ka(a)&&-1==w.m.indexOf(a))return w.m+=a,f;ka(a)&&n.console&&n.console.log("WARNING: "+('Module "'+a+'" already enabled!'));return l};s.isc=function(a){return a&&382<=a};s.cfg=function(a){return w[a]};s.ism=ka;var ta="\t\n\r";function ua(a){return a?String.trim?a.trim():a.replace(/^\s+|\s+$/g,""):k}var va=[];function C(a,b,c){a.addEventListener?a.addEventListener(b,c,f):a.attachEvent&&a.attachEvent("on"+b,c);x(va,{object:a,event:b,F:c})}
function wa(a){try{var b=a.tagUrn;if(b&&-1!=b.indexOf("schemas-microsoft-com:vml"))return f}catch(c){return f}return l}function xa(a){var b=0;if(a)for(var c=a.length,d=0;d<c;d++)b=31*b+a.charCodeAt(d),b&=b;return b}function ya(a,b){if(n.sessionStorage)try{n.sessionStorage[a]=b;return}catch(c){}u(a,b)}function za(a){return n.sessionStorage?n.sessionStorage[a]:t(a)}var Aa={"!":"%21","~":"%7E","*":"%2A","(":"%28",")":"%29","'":"%27",$:"%24",";":"%3B",",":"%2C"},Ba={"^":"^^","|":"^p",",":"^c",";":"^s"};
function v(a){a=encodeURIComponent(a);var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),e=Aa[d];e?x(b,e):x(b,d)}return b.join("")}function D(a){var b=[];if(a)for(var c=0;c<a.length;c++){var d=a.charAt(c),e=Ba[d];e?x(b,e):x(b,d)}return b.join("")}function E(a){if(a){for(var b=[],c=0;c<a.length;c++){var d=a.charAt(c),e=w.spc;e||(e="");e+=ta;-1==e.indexOf(d)&&x(b,d)}a=b.join("")}return a}function Ca(){var a=document.location.href,b=a.indexOf("#");0<=b&&(a=a.substr(0,b));return a}
function Da(a){var b=t("dtLatC"),c=0,d=[],e=0;if(b&&0<b.length){b=b.split("|");1<b.length&&(e=b.length-1);9<e&&(e=9);for(var h=1;h<=e;h++)c+=parseFloat(b[h]),d[h+1]=b[h]}e++;d[0]=~~((c+a)/e);d[1]=a;u("dtLatC",d.join("|"));return d[0]}function Ea(){return"undefined"!=typeof n.performance&&n.performance.timing&&(!y.ff||9<y.ff)?n.performance:k}var Fa={};
function Ga(a,b,c,d){if(Object.defineProperty&&(!y.ie||8<y.ie))Fa[b]=a[b],Object.defineProperty(a,b,{get:function(){return c?c.apply(a,k):Fa[b]},set:function(c){Fa[b]=c;d&&d.apply(a,[c]);return Fa[b]},configurable:f})}function Ha(a,b){if(a[b]&&Object.defineProperty&&(!y.ie||8<y.ie)){var c=a[b];delete a[b];Fa[b]=k;a[b]=c}}s.ael=C;s.lv=za;s.sv=ya;s.gh=function(a){return-1==a.indexOf("://")?k:a.split("/")[2].split(":")[0].toLowerCase()};
s.cvs=function(a,b,c,d){if(w.ffi)return f;d||(d="");for(var e=l,h=l,g=l,q=0;q<a.length&&(!e||!h);)a[q]=a[q].split("."),e=a[q][0]==b?f:l,h=a[q][1]==c?f:l,!g&&e&&(g=f),q++;if(e&&h)return f;if(g)return Ia(d+" version ("+b+"."+c+") official not supported"),f;Ia(d+" not instrumented because version ("+b+"."+c+") not supported");return l};s.esc=v;s.aesc=D;s.ulc=Da;s.gP=Ea;s.apl=Ga;s.rpl=Ha;s.dbg=function(a){u("dtUseDebugAgent",a)};s.dbc=function(a){u("dt_dbg_console",a)};
var Ja=6E8,Ka="dtPC",F=m()%Ja+"_"+~~(1E3*Math.random());s.b=F;function La(){var a=t(Ka),b=[];if(a&&"-"!=a)for(var a=a.split("|"),c=0;c<a.length;c++){var d=a[c].split("#");if(2==d.length&&d[0]&&d[1]){var e=d[0],h=~~e.split("_")[0],g=m()%Ja;g<h&&(g+=Ja);h+9E5>g&&x(b,{b:e,l:d[1]})}}return b}function Ma(){var a=La();if(0<a.length){for(var b=[],c=0;c<a.length;c++)a[c].b!=F&&x(b,a[c]);Na(b)}}
function Na(a){var b="";if(a){for(var b=[],c=0;c<a.length;c++)0<c&&x(b,"|"),x(b,a[c].b),x(b,"#"),x(b,a[c].l);b=b.join("")}b||(b="-");u(Ka,b)}s.gFId=function(){return F};s.gDtc=function(){var a=t("dtCookie");if(a){var b=a.indexOf("|");-1!=b&&(a=a.substring(0,b))}return a};s.gPAH=function(a){a=F+"#"+s.esc(a);var b=t(Ka);return b&&0<=b.indexOf(a)?k:a};var Oa=0,Pa=0,G=k,Qa=void 0,Ra=w.wi,Sa=l;
function Ta(a){for(var b=0,c=document.getElementsByTagName("img"),d=0;d<c.length;d++)""!=c[d].src&&(b+=a(c[d]));c=document.getElementsByTagName("input");for(d=0;d<c.length;d++)"image"==c[d].type&&""!=c[d].src&&(b+=a(c[d]))}function Ua(){Ta(function(a){a.z=f})}function Xa(a){Ta(Ya);G||(G=[]);x(G,a);Pa===Oa&&Za()}function Ya(a){a.z||(a.z=f,y.v&&a.complete||a.naturalWidth||(C(a,"load",$a),C(a,"error",$a),a.src=a.src,Oa++))}function $a(){Pa++;Pa===Oa&&Za()}
function Za(){if(G){for(var a=0;a<G.length;a++)G[a]();G=k}}Ra&&(Qa="all"==Ra,Sa=f);s.g=k;s.n=k;s.C=0;var ab=k,bb,cb,db={};try{r&&(r!=self&&r.dT_&&r.dT_.version==s.version)&&(cb=r.dT_,ab=r.dT_.tdto())}catch(eb){}ab?(s.g=ab.g,s.n=ab.n,bb=cb.b,cb.C++):(s.g=F,s.n=document.title);s.tp=function(){return!ab};s.tdto=function(){try{if(r&&r!=self&&r.dT_)return r.dT_.tdto()}catch(a){}return s};s.aFU=function(a){a=D(a);db[a]||(db[a]="1")};s.iRO=function(a){return"1"==db[a]};
function fb(a,b,c,d){for(var e=3,h=0;0<e;)try{var g=da(),h=m();a(g);g.open("POST",b,c);g.setRequestHeader("Content-Type","text/plain;charset\x3dUTF-8");g.send(d);e=0}catch(q){e--}return h}var H=k,gb=[],hb=l,ib=l,jb,kb=f,lb,mb;function nb(){var a=this;a.f=[];a.a=function(b,c){x(a.f,[b,c])}}function ob(a){Da(a/2)}function pb(a,b,c){qb(a,b,l);H&&rb(l,c)}
function qb(a,b,c){var d="";if(a){c="";for(var e in I)I.hasOwnProperty(e)&&(c=c?c+",":c,c+=sb(I[e],l,l,f))}else{e="";d=J.length;b&&(I=[]);if(0<d){for(b=0;b<d;b++){var h=sb(J[b],f,c,l);h&&0<h.length&&(K&&"_load_"==J[b].type&&(e=K.B?"d|"+K.name+"|"+K.type+"|"+K.b+"|"+K.start+"|"+K.location+"|"+K.title:"s|"+K.name+"|"+K.type+"|"+K.b+"|"+K.start,K=k),0<e.length&&(e+=","),e+=h)}J=[];for(var g in I)I.hasOwnProperty(g)&&x(J,I[g])}c=e}d=c;H=k;0<d.length?(H=new nb,H.a("a",v(d)),H.a("fId",F),a&&H.a("PV",1),
s.g!=F&&H.a("pId",s.g),bb&&H.a("pFId",bb),H.a("rId",w.rid),H.a("rpId",w.rpid),a||(ib||H.a("title",v(E(document.title))),(c=tb())&&H.a("domR",c),ib=f),ub()&&H.a("unload","xhr"),vb(a)):kb===l&&(H||(H=new nb),c=H.f.length,vb(a),H.f.length>c?H.a("fId",F):H=k);kb=l}function vb(a){for(var b=0;b<gb.length;b++)gb[b](H,a)}function wb(){for(var a=[],b=0;b<H.f.length;b++)0<b&&x("$"),x(a,"$",H.f[b][0],"\x3d",H.f[b][1]);return a.join("")}
function xb(){var a=wb(),b=y.ie?1500:7E3;w.msl&&(b=Math.min(b,~~w.msl));return 0===a.length%b?~~(a.length/b):~~(a.length/b)+1}
function rb(a,b){function c(a){a.onreadystatechange=function(){if(4==a.readyState&&200==a.status){var b=m()-e;d&&d(b)}}}var d=ob,e=m();H.a("time",e);var h=yb(),g=xb(),q=y,L;L=!a||a&&!(q.sf||q.op||q.ff&&(1<g||w.sffs||17<q.ff)||q.ie&&(9>q.ie||w.sies)||q.msf||q.ab||q.ch&&22<q.ch);b&&(L=!b);q=1==g&&a&&(q.ie&&9>q.ie||q.ch);if(h!==k)if(g=w.reportUrl?w.reportUrl:"dynaTraceMonitor",q)L=document.createElement("img"),d&&(L.onerror=function(){d(m()-e)}),L.setAttribute("src",g+"?"+h[0]);else{var q=g,Va=h[0];
if(w.spl)for(var Wa=0;Wa<h.length;Wa++)Va=k,q=g+"?"+h[Wa],e=fb(c,q,L,Va);else e=fb(c,q,L,Va)}}
function yb(){var a=wb(),b=k;if(w.spl){var c=y.ie?1500:7E3;w.msl&&(c=Math.min(c,~~w.msl));var d=xb(),e,h=m(),g=0;if(1<d){if(100>d)for(var b=[],q=0;q<d;q++){var L="sid\x3d"+h+"\x26p"+(q+1)+"_"+d+"\x3d";g+c<=a.length?(e=a.slice(g,g+c),"%"==e.charAt(e.length-1)&&a.length>=g+c+1&&(e+=a.charAt(g+c),e+=a.charAt(g+c+1),g+=2),"%"==e.charAt(e.length-2)&&a.length>=g+c+2&&(e+=a.charAt(g+c),g+=1)):e=a.slice(g);x(b,L+e);g+=c}}else b=[a]}else b=[a];return b}
function tb(){var a=Ea();if(a&&a.timing){if(a.timing.domComplete&&0<a.timing.domComplete)return a.timing.domComplete;if(a.timing.s&&0<a.timing.s)return a.timing.s}return jb}function zb(a){hb&&m()+a<mb&&(clearTimeout(lb),hb=l);hb||(mb=m()+(a?a:0),lb=p(Ab,void 0!=a?a:0),hb=f)}function Ab(){hb=l;pb(l,l,l)}s.ss=function(a,b,c){pb(b,c,a)};s.asl=function(a){x(gb,a)};s.sMPS=function(a){zb(a)};var M=k,J=[],I=[],Bb=[],Cb=0,N=[],O=[],Db=w.wi,P;s.u=Eb;var Fb=[];
function Q(){for(var a=0;a<Fb.length;a++)Fb[a]()}function Eb(){return I}function Gb(a,b,c,d,e,h){var g={start:c,stop:d,type:a,name:b,i:e,next:[],e:k,p:k,w:k,o:k,d:k,count:k,q:h?~~(2147483647*Math.random())+1:0,add:function(a){a&&a.name&&x(g.next,a)}};Bb[g.name]?(Bb[g.name]++,g.d=g.name,g.count=Bb[g.name],g.name+="#"+g.count):Bb[g.name]=1;return g}
function Hb(){var a=l,b=[],c;for(c in I)if(I.hasOwnProperty(c)){var d=I[c];0<d.p&&(m()>d.e&&(d.e+=6E4,x(b,d)),a=f)}0<b.length&&pb(f,f,l);for(c=0;c<b.length;c++)b[c].p--;a&&p(Hb,1E3)}function Ib(a,b){if(a)for(var c=k,d=0;d<a.length;d++){c=a[d];if(c.name==b||c.d&&c.d==b)return c;if(c.next&&(c=Ib(c.next,b),c!==k))return c}return k}function Jb(a){var b=k;J&&(b=Ib(J,a));return b}
function Kb(a,b,c,d,e){c||(c=m());a=Gb(b,a,c,k,k,e);"boolean"==typeof d&&d&&(d=M);if(d){if(b=k,b="string"==typeof d?Jb(d):"object"==typeof d?d:M){b.add(a);Lb(a);for(var h in I)I.hasOwnProperty(h)&&(I[h]&&I[h].e>a.start+1E4)&&(I[h].e=a.start+1E4)}}else Lb(a),Mb(a),x(I,a),M=a,x(J,a),a.e=a.start+1E4,a.p=100,p(Hb,5E3);return a}function Lb(a){if(M!=a)if(M=a){a=a.name;for(var b=La(),c=l,d=0;d<b.length;d++)b[d].b==F&&(b[d].l=v(a),c=f);c||x(b,{b:F,l:v(a)});Na(b)}else Ma()}
function Nb(a,b,c){b||(b=m());var d=[];if(J)for(var e=0;e<J.length;e++)d[e]=Ob(J[e],a,b,c);a=l;for(b=0;b<J.length;b++)if(d[b])a=d[b];else{R=k;c=[];for(var h in I)if(I.hasOwnProperty(h))if(e=I[h],e.name===J[b].name&&e.type===J[b].type)x(c,h);else if(P){var g=cb.u();e.w=r&&g[g.length-1]==P?"S":"A";P=k}for(e=0;e<c.length;e++){var g=c[e],q=I;q.splice(g,g-(g||NaN)+1||q.length)}}zb(0);Lb(a)}
function Ob(a,b,c,d){var e;a.d&&a.d==b||a.name==b?(a.stop=c,d&&(a.start=d),a.i=document.getElementsByTagName("*").length):a.stop||(e=a);if(a.next&&0<a.next.length)for(var h=1;h<=a.next.length;h++){var g=Ob(a.next[a.next.length-h],b,c,d);g&&(e=g)}return e}function sb(a,b,c,d){if(a.o){var e=[],h=["0"];h[1]=a.o;h[2]=a.w;e[0]=h.join("|");e[1]=Pb(a,1,b,c,d);return e.join(",")}return Pb(a,1,b,c,d)}
function Pb(a,b,c,d,e){a.i||(a.i=document.getElementsByTagName("*").length);var h=[];if(a.next&&0<a.next.length){for(var g=0;g<a.next.length;g++){var q=Pb(a.next[g],b+1,c,d,e);if(q)h.push(q);else return k}c&&(c=a.next[a.next.length-1],c.stop?a.stop&&c.stop>a.stop&&(a.stop=c.stop):a.stop=void 0)}if(!d&&!e&&(!a.stop||0==a.stop))return k;d=[];d[0]=b.toString();d[1]=D(a.d?a.d:a.name);d[2]=a.count?a.count:"-";d[3]=D(a.type);d[4]=a.start;d[5]=a.stop?a.stop:0;d[6]=a.i;1==b&&a.h&&(d[7]=a.h);a.q&&(d[7]||(d[7]=
"-"),d[8]=a.q);h.unshift(d.join("|"));return 1<h.length?h.join(","):h[0]}function ub(){if(0<Cb){var a=N.length;if(0<a)return N[a-1]}return k}function Qb(a,b,c){var d=k;1==arguments.length&&(b=3);var e=Rb(),h=k;e&&e.r&&(h=e.r);h||(h=ub());h?d=Sb(h):e?3<=b&&(d=Tb(e.getName(),e.type,e.start,k,c),e.r=d,Db&&Ua()):M?1<=b&&(d=Sb(M.name,a,"xhr",m(),c),Db&&Ua()):w.cux&&(d=Tb("Unlinked XHR","xhr",m(),k,c));return d}function Tb(a,b,c,d,e){a=Kb(a,b,c,d,e);a.k=1;O[a.name]=a;return a.name}
function Sb(a,b,c,d,e){a=O[a];var h;a?(a.k++,h=a.name):M&&(h=Tb(b,c,d,M.name,e));return h}function Ub(a){var b=0;if(b=O[a])b.k--,b=b.k,0>=b&&(Nb(a),O[a]=k,delete O[a])}function Vb(){var a=0,b;for(b in O)if(b&&O.hasOwnProperty(b))try{a+=O[b].k}catch(c){}return a}function Mb(a){P=k;if(cb){var b=cb.u();if(P=b[b.length-1])a.o=P.name,P.h?P.h++:P.h=1}}function S(a,b,c){var d=m();a=E(a);b=Gb(b,a,d,d,-1);Wb(b,c)&&zb(5E3)}function Wb(a,b){var c;if(c=b?Jb(b):M)return c.add(a),l;Mb(a);x(J,a);return f}
function Ia(a,b){S(a,"_warning_",b)}s.ea=function(a,b,c,d){if(4>arguments.length||"undefined"==typeof d)d=f;return Kb(a,b,c,d).name};s.la=function(a,b,c){Q();Sa&&Qa?Xa(function(){Nb(a,b,c)}):Nb(a,b,c)};s.lx=function(a){if(1<Vb())p(function(){Ub(a)},0);else return Db?Xa(function(){p(function(){Ub(a)},0)}):p(function(){Ub(a)},0),Q(),f;return l};s.ex=Qb;s.ec=function(a){a&&(x(N,a),Cb++)};
s.lc=function(a){a&&(Cb--,p(function(){for(var b=-1,c=N.length-1;-1==b&&0<=c;)N[c]==a&&(b=c),c--; -1!=b&&(b==N.length-1?N.pop():N.splice(b,1))},0))};s.pcn=S;s.pe=function(a,b){S(a,"_error_",b)};s.pw=Ia;s.pl=function(a,b){S(a,"_log_",b)};s.ewa=function(a){a=Qb(a,3,f);return Jb(a)};s.gWRI=function(a){return a.q};s.gAN=function(a){return a.name};s.rv=function(a,b){var c=m(),c=Gb("_rv_",a+"\x3d"+b,c,c,0);Wb(c);zb(5E3)};s.rs=function(a,b){var c=m(),c=Gb("_rs_",a+"\x3d"+b,c,c,0);Wb(c);zb(5E3)};s.ca=function(){return M};
s.noa=function(){return!M||0<M.stop};s.ti=Q;var Xb,Yb=l;function Zb(a){11>y.ie?S(n.event.type+":"+n.event.errorUrl+"["+n.event.errorLine+"] Code: "+n.event.errorCode+": "+n.event.errorMessage,"_error_"):S(a.type+":"+a.filename+"["+a.lineno+":"+a.colno+"] "+a.message,"_error_")}
function $b(a,b,c){if(!Yb){Yb=f;var d=k;try{if(d="object"==typeof a?a.srcElement?a.srcElement.outerHTML&&200>a.srcElement.outerHTML.length?document.URL.split("#")[0]+"[-]: Error at '"+a.srcElement.outerHTML+"'":document.URL.split("#")[0]+"[-]: Error at tag: '"+a.srcElement.tagName+"'":"unknown error":"undefined"===typeof b||"undefined"==b?a:b+"["+c+"]: "+a){var e=Rb();e&&(d+=", user action: "+e.getName());S(d,"_error_")}}catch(h){}Xb&&(Xb!=$b&&"function"==typeof Xb)&&Xb(a,b,c);Yb=l}return l}
y.ie?C(n,"error",Zb):n.onerror!=$b&&(n.onerror&&(Xb=n.onerror),n.onerror=$b);try{Ga(window,"onerror",function(){return $b},function(a){Xb=a})}catch(ac){}C(n,"unload",function(){Ha(window,"onerror");n.onerror=k});var bc="BUTTON",cc="INPUT",dc="HIDDEN",ec="SUBMIT",fc="RESET",gc="IMAGE",hc="IMG",ic="A",jc="FORM",kc="HTML",lc="BODY",mc="HEAD",nc="SELECT",oc="unknown",qc=pc(n.location.href),rc=0,sc=1,tc=2,uc=3,vc=4,wc=0;
function xc(a){if(a)for(var b=document.getElementsByTagName("LABEL"),c=0;c<b.length;c++)if(b[c].htmlFor==a)return a=b[c],T(a.innerText,a.textContent);return k}function T(a){for(var b=0;b<arguments.length;b++){var c=arguments[b];if(c&&ua(c))return ua(c)}return k}function yc(a){return a&&(a=a.split("/"),0<a.length)?a[a.length-1].split(".")[0]:k}function pc(a){if(a){var b=a.split("/");if(0<b.length&&(b=ua(b[b.length-1]),b!==k))return b}return a}
function zc(a,b){if(!b||0>=b.length||20<wc)return k;for(var c=0;c<b.length;c++){var d=b[c];if(y.ie&&wa(d))return"VML Node";var e=d.nodeName?d.nodeName.toUpperCase():oc,h=d.type?d.type.toUpperCase():k,g=k;wc++;if(g=zc(a,d.childNodes))return g;wc--;switch(a){case rc:e==cc&&h!=dc&&(e=h&&(h==bc||h==ec||h==fc||h==gc)?d.value:k,g=xc(d.id),g=h&&(h==bc||h==ec||h==fc)?T(e,g):T(g,e));g||(g=T(d.textContent,d.innerText));break;case sc:if(e==cc&&h!=dc||e==bc)g=T(d.name,d.title,h&&h==gc?d.alt:k);break;case tc:e==
cc&&h==gc?g=yc(d.src):e==ic?g=T(d.title,pc(d.href)):e==hc?g=T(d.name,d.title,d.alt,yc(d.src)):e==jc&&(g=T(d.name,d.id,d.action));g||(g=T(d.title,d.data,d.wholeText,d.id));break;case uc:g=d.className;break;case vc:g=e==cc&&h!=dc?cc+": "+h:e==ic?"LINK":e}if(g)return g}return k}
function Ac(a){if(y.ie&&wa(a))return"VML Node";if("string"==typeof a)return a;if(a.attributes){var b=a.attributes["data-dtName"];if(b&&b.value)return b.value}b=a.nodeName?a.nodeName.toUpperCase():oc;if(b==kc||b==lc||b==mc)return"Page: "+qc;if(b==nc){if(a)if(b=a.nodeName?a.nodeName.toUpperCase():k,b!=nc)a=k;else{var c=xc(a.id),b=T(c,a.name,b),c=k;a.multiple||(a=a.options&&-1<a.selectedIndex?a.options[a.selectedIndex]:k)&&(c=T(a.label,a.innerText,a.textContent));a=c?"["+b+"] to value ["+c+"]":b}else a=
k;return a}if(b=ua(T(a.innerText,a.textContent)))return b;wc=0;a:{a=[a];b=zc;for(c=0;4>=c;c++){var d=b(c,a);if(d){a=d;break a}}a=k}return a}var U,Bc=0,Cc=f,V=s.tdto(),Dc=[[13,"\x3cRETURN\x3e"],[9,"\x3cTAB\x3e"],[8,"\x3cBACKSPACE\x3e"],[127,"\x3cDELETE\x3e"],[27,"\x3cESCAPE\x3e"],[33,"\x3cPAGE UP\x3e"],[34,"\x3cPAGE DOWN\x3e"],[116,"\x3cF5\x3e"]];
function Ec(a,b,c,d){if(s!=V)return V.bi(a,b,c,d);try{var e={id:Bc++,c:a,name:k,type:b,start:m(),A:l,H:m()+(4<=arguments.length?d:30),getName:function(){if(!e.name){var a=E(Ac(e.c));a||(a="-");var b=w.sl||100;a.length>b&&(a=a.substring(0,b-3)+"...");e.name=e.type?e.type+' on "'+a+'"':a}return e.name},D:function(){return e.A},G:function(){var a=e;do a.A=f,a=a.next;while(a)}};Cc&&(e.next=U,e.next&&(e.next.j=e),U=e);return e}finally{e&&p(function(){Fc(e)},30)}}
function Rb(){if(s!=V)return V.gci();try{if(U){for(var a=U,b=U.next;b;){var c;if(c=b.c!=a.c)a:{for(var d=b.c.parentNode;d;){if(d==a.c){c=f;break a}d=d.parentNode}c=l}c&&(a=b);b=b.next}return a}return k}catch(e){return k}}function Gc(){for(var a=U;a;)a.c=k,a=a.next;U=k}function Fc(a){if(s!=V)return V.ei(a);if(U){for(var b=U;b.next&&b!==a;)b=b.next;b===a&&(b.c=k,b.j?b.j.next=b.next:U=b.next,b.next&&(b.next.j=b.j))}}
function W(a,b,c){var d=l,e=w.doNotDetect?w.doNotDetect.split(","):k;if(c&&e)for(var h=0;h<e.length;h++)e[h]==c&&(d=f);d||(b||(b=a),C(document,a,function(a){var c=k;a.target?c=a.target:a.srcElement&&(c=a.srcElement);var d=b;if("keypress"==d){a:{a=a.keyCode?a.keyCode:a.charCode;for(var e=0;e<Dc.length;e++)if(Dc[e][0]==a){a=Dc[e][1];break a}e=String.fromCharCode(a);a="a"<=e&&"z">=e||"A"<=e&&"Z">=e||"0"<=e&&"9">=e?e:a}a&&(d+=" "+a)}Ec(c,d,k,30)}))}W("click","click","clk");W("mousedown","click","mdw");
W("mouseup","click","mup");W("dblclick","dblclick","dcl");W("keydown","keypress","kyd");W("keyup","keypress","kyu");W("scroll","scroll","scr");W("touchstart","touch","tcs");W("touchend","touch","tce");if(w.ade){var Hc=w.ade.split(",");if(Hc&&0<Hc.length)for(var Ic=0;Ic<Hc.length;Ic++)W(Hc[Ic])}s.bi=Ec;s.ei=Fc;s.gci=Rb;s.ci=function(){return s!=V?V.ci():Rb()?U.getName():k};s.aad=function(a){(Cc=a)||Gc()};var Jc=l,Kc=l,Lc=l,K=k,R=k,Mc=za("dtSa");ya("dtSa","-");
if(Mc&&"-"!=Mc){var X=Mc.split("|");if(7==X.length){var Nc={B:"true"==X[0],type:X[1],name:X[2],start:X[3],b:X[4],location:X[5],title:X[6]},Oc=l;s!=s.tdto()&&(Oc=s.tdto().iRO(Nc.location));if(!document.referrer||Nc.location==D(document.referrer)||Nc.location==D(document.location)||Oc)R=K=Nc}}var Pc=k,Qc=l,Rc=[],Sc=[],Tc=l,Uc=l,Vc=1;s.tdto().aFU(document.location.href);
if(!w.rid){var Wc=w.ridPath,Xc=Wc?Wc:n.location.pathname,Yc=n.location.search;Yc&&0<Yc.length&&"?"==Yc.charAt(0)&&(Yc=Yc.substring(1));var Zc=Yc,Y=1,Y=31*Y+xa(Xc),Y=31*Y+xa(Zc),Y=Y&Y;w.rid="RID_"+Y}var Z=k,$c,ad=Ea();ad&&(Z=ad.timing);function bd(){if(Z){var a;a=0<Z.redirectStart?Z.navigationStart+6E4>Z.redirectStart?Z.navigationStart:Z.redirectStart:Z.navigationStart+6E4>Z.fetchStart?Z.navigationStart:Z.fetchStart;return a<aa-2E4||a>aa+2E4?aa:a}return aa}
function cd(){Vc--;if(0>=Vc){var a=Z?Z.loadEventEnd:0,b;b=Z?Z.loadEventStart:0;b=b<bd()?0:b;Pc&&(a&&b?Nb(Pc.name,a,b):Nb(Pc.name),Pc=void 0);$c||dd()}}function dd(){ed&&(Nb(ed.name),ed=k,Q())}function fd(){Pc||(Pc=Kb("_onload_","_load_",k,ed))}s.sls=function(){};s.sole=cd;s.iolm=function(){Vc++};s.solb=fd;s.slem=function(){$c=f};s.lst=bd;function gd(){if(!Kc){Kc=f;Q();for(var a=0;a<Rc.length;a++)try{Rc[a]()}catch(b){}cd()}}function hd(){Q();Jc||(fd(),Jc=f,p(gd,0))}
function id(){Q();Jc||("complete"==document.readyState?Lc?pb(l,f,l):(Lc=f,p(id,3E3)):p(id,3E3))}function jd(a,b,c){var d=ub();!d&&a&&b&&c?ya("dtSa","true|"+D(b)+"|"+D(a)+"|"+c+"|"+F+"|"+D(Ca())+"|"+D(E(document.title))):d&&R?(ya("dtSa","false|"+R.type+"|"+R.name+"|"+m()+"|"+R.b+"|"+D(Ca())+"|"+D(E(document.title))),R=k):M&&"_load_"!=M.name&&ya("dtSa","false|"+D(M.type)+"|"+D(M.name)+"|"+m()+"|"+F+"|"+D(Ca())+"|"+D(E(document.title)))}function kd(){ld()}
function ld(a){if(!Tc){Tc=!a;for(a=0;a<Sc.length;a++)Sc[a](Tc);qb(l,f,f);(a=Rb())&&a.D()===l?(a.G(),jd(a.getName(),a.type,a.start)):jd(k,k,k);if(y.sf&&n.frames)for(a=0;a<n.frames.length;a++)try{n.frames[a].dT_&&n.frames[a].dT_.obc()}catch(b){}H&&rb(f,l)}}C(n,"beforeunload",kd);
C(n,"unload",function(){ld();if(!Uc)try{Gc();var a;for(a=0;a<va.length;a++){var b=va[a],c=b.object,d=b.event,e=b.F;y.v&&9>y.v?c.detachEvent("on"+d,e):c.removeEventListener?c.removeEventListener(d,e,l):c.detachEvent&&c.detachEvent("on"+d,e)}Z=ca=ba=va=k;Uc=f}catch(h){}Qc||(Qc=f,Ma())});C(n,"pagehide",function(){ld(f);Qc||(Qc=f,Ma())});C(document,"readystatechange",function(){"loaded"==document.readyState&&Q();"complete"==document.readyState&&hd()});p(id,3E3);C(n,"load",hd);
(function(){if(y.ie){var a=function(){var b=document.createElement("doc:rdy");try{b.doScroll("left"),jb=m(),Q()}catch(c){p(a,0)}};a()}else document.addEventListener("DOMContentLoaded",function(){jb=m();Q()},l)})();var ed=Kb("_load_","_load_",bd(),k);Q();s.all=function(a){x(Rc,a)};s.ail=function(a){x(Fb,a)};s.apll=function(a){x(Sc,a)};s.sle=dd;s.obc=kd;s.ile=function(){return 0>=Vc};var $=window.dT_,md=[],nd=l;function od(a){nd?a($.bwsW,$.bwsH):md.push(a)}
$.all(function(){var a=document,b=a.documentElement,c=0,d=0;if("number"==typeof self.innerWidth)c=self.innerWidth,d=self.innerHeight;else if(a&&(b.clientWidth||b.clientHeight))c=b.clientWidth,d=b.clientHeight;else if(a.body&&(a.body.clientWidth||a.body.clientHeight))c=a.body.clientWidth,d=a.body.clientHeight;if(0<c&&0<d)a=screen.availWidth,b=screen.availHeight,c=c<a?c:a,d=d<b?d:b;else{var e;$.gBI().ie?e=140:e=10;c=Math.max(c,e);d=Math.max(d,10)}$.bwsW=c;$.bwsH=d;nd=f;for(a=0;a<md.length;a++)md[a](c,
d)});$.abwsl||($.abwsl=od);var pd=f;$.asl(function(a,b){if(!b&&pd){pd=l;var c=$.tdto(),d=function(a){return 0>a||2147483647<=a||isNaN(a)?0:a};c?(a.a("w",d(c.bwsW)),a.a("h",d(c.bwsH))):(a.a("w",d($.bwsW)),a.a("h",d($.bwsH)))}});
})();(function() {
var d=!0,e=null,f=!1,g,h=window.dT_,k,l,m,n,p,q,r,s,u,v,w="onclick",x="onmouseup",y="dT_handler",z=[];function A(a,b){a[y+b]=d;a[y]||(z[z.length]=a,a[y]=d)}function B(){if(z){for(var a=0;a<z.length;a++){var b=z[a];b.onclick&&(b.onclick.toString=e);b.onclick=e;b.onmouseup&&(b.onmouseup.toString=e);b.onmouseup=e;b.onchange&&(b.onchange.toString=e);b.onchange=e;b.onblur&&(b.onblur.toString=e);b.onblur=e;z[a]=e}z=e}}
function D(a,b,c,C){if(c&&(a[b]||b==x&&v)&&!a[y+b]){A(a,b);var t=a[b];a[b]=function(){var c=b.replace("on","");h.bi(a,C||c,c+" wrapper");c=e;t&&(c=t.apply(this,arguments));return c};r&&(a[b].toString=function(){if(t)return t.toString()})}}
function E(){if(k||l||m||n||p||q)if("function"==typeof document.createTreeWalker&&"undefined"!=typeof NodeFilter)for(var a=document.createTreeWalker(document,NodeFilter.SHOW_ALL,e,f);a.nextNode();)F(a.currentNode);else{var a=document.getElementsByTagName("*"),b=a.length,c;if(!(c=!h.gBI().ie))if(!(c=9<=h.gBI().ie))c=parseInt(h.cfg("mdn"),10),c=b<(isNaN(c)?5E3:c);if(c)for(c=0;c<b;c++)F(a[c]);else s||(s=d,h.pw("Document has "+b+" DOM nodes. Disabling instrumentation!"))}}
function F(a){try{D(a,x,l||v,"click"),D(a,w,k&&!v)}catch(b){}for(var c=0;c<u.length;c++)try{3==u[c].length?D(a,u[c][0],u[c][1],u[c][2]):D(a,u[c][0],u[c][1])}catch(C){}}if(h.smbi("a")){g=h.cfg("instr");v=h.cfg("ncw");q=p=n=m=r=l=k=f;var G=0;if(g)for(var H=g.split(","),G=0;G<H.length;G++){var I=H[G];"clk"==I?k=d:"mup"==I?l=d:"tos"==I?r=d:"blr"==I?m=d:"chg"==I?n=d:"tcs"==I?p=d:"tce"==I&&(q=d)}u=[["onblur",m],["onchange",n]];h.ael(window,"unload",B);h.ail(E)};
})();(function() {
var a=window.dT_,b=-1,d=0,f=-1,g=0,h="",k=0,l=-1,m=a.gDtc(),n=m&&"_m"==m.substr(m.length-2);function p(){var c=a.nw(),c=h+"dynaTraceMonitor?bwstate\x3d"+d+"\x26unique\x3d"+c;a.gBI().ie&&(c+="\x26ie\x3d"+a.gBI().ie);var e=document.createElement("img");e.setAttribute("src",c);var s=!1;l=a.nw();e.onload=e.onreadystatechange=function(){if(!s&&(!e.readyState||"complete"==e.readyState))s=!0,q()};var u=!1;e.onerror=function(){!u&&1==d&&(u=!0,q())}}
function q(){var c=!1;f=a.nw()-l;0===d&&(g=a.ulc(f/2));if(0!==d&&(6<=d||f>100+g))k=1,c=!0,a.sMPS(2E3);r();d++;c||a.st(p,100)}function t(){k&&a.nw()-l<b||(k&&(d=0),k=0,a.st(p,100))}function r(){a.sv("dtbw",l+"|"+d+"|"+f+"|"+g+"|"+k)}var v=!1,w=a.cfg("bandwidth");
if(w&&(a.tp()&&a.smbi("b"))&&(n&&(-1==w.indexOf("m")?v=!0:w=w.substr(0,w.length-2)),!v)){var b=1E3*parseInt(w,10),x=decodeURIComponent(a.cfg("reportUrl"));if(x){var y=x.lastIndexOf("/");0<=y&&(h=x.substring(0,y+1))}var z=a.lv("dtbw");if(z){var A=z.split("|"),l=A[0];a.nw()-l<b&&5==A.length&&(l=A[0],d=A[1],f=isNaN(A[2])?0:A[2],g=isNaN(A[3])?0:A[3],k=parseInt(A[4],10))}a.asl(function(c,e){!e&&(0<d&&k)&&(c.a("bw",d+"_"+f),r(),a.st(t,b))});a.st(t,2E3)};
})();(function() {
var h=null,k=window.dT_,l=window.XMLHttpRequest,m=window.ActiveXObject,p=window.document.all&&!window.opera;function r(c){function d(a){try{c.a[a]=function(){if(c.c)for(var e=a.substring(2),f=0;f<c.c.length;f++)if(c.c[f][0]===e){c[a]=c.c[f][1];break}if(c[a])try{k.ec(c.b),c[a].apply(c,arguments)}finally{k.lc(c.b)}}}catch(q){}}for(var a=["onloadstart","onloadend","onerror","onprogress","onload"],g=0;g<a.length;g++)d(a[g])}function s(c){c.a.onreadystatechange=function(){};delete c.headers}
function t(c,d,a){d=d.toLowerCase();for(var g=1<<d.length,b=0;b<g;b++){for(var q=d.split(""),e=0;e<d.length;e++)b>>e&1&&(q[e]=q[e].toUpperCase());c[q.join("")]=a}}
function u(c){function d(){a.readyState=a.ReadyState=a.a.readyState;var b=a;try{b.responseText=b.ResponseText=b.a.responseText}catch(c){}try{var e;var f=b.a,n=f.responseXML;if(p){if(p&&n&&!n.documentElement&&f.getResponseHeader("Content-Type").match(/[^\/]+\/[^\+]+\+xml/)){var d=new window.ActiveXObject("Microsoft.XMLDOM");d.loadXML(f.responseText)}if(d&&!(p&&d.parseError&&0!==d.parseError.errorCode||d.documentElement&&"parsererror"==d.documentElement.tagName))n=d}e=n;b.responseXML=b.ResponseXML=
e}catch(v){}try{b.response=b.Response=b.a.response}catch(w){}try{b.status=b.Status=b.a.status}catch(x){}try{b.statusText=b.StatusText=b.a.statusText}catch(y){}try{b.responseBody=b.ResponseBody=b.a.responseBody}catch(z){}try{b.responseStream=b.ResponseStream=b.a.responseStream}catch(A){}4==a.readyState&&(s(a),p&&a.async&&window.detachEvent("onunload",g));if(a.d!=a.readyState){b=a;try{k.ec(b.b),b.dispatchEvent({type:"readystatechange",bubbles:!1,cancelable:!1,timeStamp:new Date+0})}finally{k.lc(b.b),
4==b.readyState&&b.b&&(k.lx(b.b),b.b=h)}a.d=a.readyState}}var a=this;a.a="object"===typeof c&&"undefined"!==typeof c.name?"undefined"!==typeof c.location?new m(c.name,c.location):new m(c.name):l?new l(c):new m("Microsoft.XMLHTTP");a.c=[];a.UNSENT=0;a.OPENED=1;a.HEADERS_RECEIVED=2;a.LOADING=3;a.DONE=4;a.readyState=a.ReadyState=0;a.d=-1;a.responseText=a.ResponseText=void 0;a.responseType=void 0;a.responseXML=a.ResponseXML=h;a.response=a.Response=h;a.responseBody=a.ResponseBody=h;a.responseStream=a.ResponseStream=
h;a.status=a.Status=0;a.statusText=a.StatusText="";a.onreadystatechange=a.onReadyStateChange=a.OnReadyStateChange=h;"undefined"!=typeof a.a.withCredentials&&(a.withCredentials=a.a.withCredentials);a.timeout=0;a.upload=a.a.upload;var g=h;t(a,"open",function(b,c,e,f,n){a.e=!1;3>arguments.length&&(e=!0);a.async=e;p&&e&&(g=function(){4!=a.a.readyState&&(s(a),a.abort())},window.attachEvent("onunload",g));e&&(a.a.onreadystatechange=d);a.onopen&&a.onopen.apply(a,arguments);4<arguments.length?a.a.open(b,
c,e,f,n):3<arguments.length?a.a.open(b,c,e,f):a.a.open(b,c,e)});t(a,"send",function(b){a.b=k.ex("x");try{a.async&&(a.a.timeout=a.timeout)}catch(c){}try{a.async&&(a.a.responseType=a.responseType)}catch(e){}a.onsend&&a.onsend.apply(a,arguments);b&&b.nodeType&&(b=window.XMLSerializer?(new window.XMLSerializer).serializeToString(b):b.xml,a.headers["Content-Type"]||a.a.setRequestHeader("Content-Type","application/xml"));r(a);if(a.b){var f=k.gPAH(a.b);f&&a.a.setRequestHeader("x-dtPC",f)}a.a.withCredentials!==
a.withCredentials&&(a.a.withCredentials=a.withCredentials);a.a.send(b);a.async||d()});t(a,"abort",function(){a.onabort&&a.onabort.apply(a,arguments);0<a.readyState&&(a.e=!0);a.a.abort();s(a);a.b&&(k.lx(a.b),a.b=h)});a.getAllResponseHeaders=a.GetAllResponseHeaders=function(){return a.a.getAllResponseHeaders()};a.getResponseHeader=a.GetResponseHeader=function(b){return a.a.getResponseHeader(b)};a.setRequestHeader=a.SetRequestHeader=function(b,c){a.headers||(a.headers={});a.headers[b]=c;return a.a.setRequestHeader(b,
c)};a.a.addEventListener&&(a.addEventListener=a.AddEventListener=function(b,c,e){for(var f=h,d=0;d<a.c.length;d++)if(f=a.c[d],f[0]==b&&f[1]==c&&f[2]==e)return;a.c.push([b,c,e])},a.removeEventListener=a.RemoveEventListener=function(b,c,e){for(var d=h,g=0;g<a.c.length&&!(d=a.c[g],d[0]==b&&d[1]==c&&d[2]==e);g++);d&&a.c.splice(g,1)});a.dispatchEvent=a.DispatchEvent=function(b){b={type:b.type,target:a,currentTarget:a,eventPhase:2,bubbles:b.bubbles,cancelable:b.cancelable,timeStamp:b.timeStamp,stopPropagation:function(){},
preventDefault:function(){},initEvent:function(){}};"readystatechange"==b.type&&(a.onreadystatechange?(a.onreadystatechange.handleEvent||a.onreadystatechange).apply(a,[b]):a.onReadyStateChange?(a.onReadyStateChange.handleEvent||a.onReadyStateChange).apply(a,[b]):a.OnReadyStateChange&&(a.OnReadyStateChange.handleEvent||a.OnReadyStateChange).apply(a,[b]));for(var c=0;c<a.c.length;c++){var d=a.c[c];d[0]==b.type&&!d[2]&&(d[1].handleEvent||d[1]).apply(a,[b])}};a.toString=function(){return"[XMLHttpRequest]"}}
k.smbi("x")&&(window.XMLHttpRequest&&(window.XMLHttpRequest=u),window.ActiveXObject&&(window.ActiveXObject=function(c,d){var a=arguments;if(0===a.length)return new m;var g=c.toLowerCase();return"microsoft.xmlhttp"===g||"msxml2.xmlhttp.6.0"===g||"msxml2.xmlhttp.3.0"===g||"msxml2.xmlhttp"===g?1===a.length?new u({name:c}):new u({name:c,location:d}):1==a.length?new m(c):new m(c,d)}),k.ael(window,"unload",function(){window.XMLHttpRequest=l;window.ActiveXObject=m;p=m=l=h}));
})();(function() {
var c=window.dT_,g=window.performance,k="redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),l=!0;
c.smbi("n")&&c.asl(function(d,m){if(!m&&l)if(l=!1,"undefined"!=typeof g)if(c.gBI().ff&&9>=c.gBI().ff)d.a("nt","0");else{var a;a=g.timing||{};var b=g.navigation||{},e=a.navigationStart;if(e){for(var b=["a",b.type,"b",e],n=k.length,f=0;f<n;f++){var h=a[k[f]];h&&h>=e&&(b.push("cdefghijklmnopqrstuvwxyz".charAt(f)),b.push(h-e))}a=b.join("")}else a=null;a?d.a("nt",a):d.a("nt","0")}else d.a("nt","0")});
})();(function() {
var f=!0,k=null,q=!1,r=window.dT_;function s(a,b,e){for(var d=2;d<arguments.length;d++)a.push(arguments[d]),(d<arguments.length-1||b)&&a.push("|")}
function t(){this.head=k;this.add=function(a,b){if(a>b)throw"Error: Start("+a+") must be before stop ("+b+")";var e={start:a,stop:b},d=this.head,g=k;if(d){for(;d&&a>d.start;)g=d,d=d.next;g?(e.next=g.next,g.next=e):(e.next=this.head,this.head=e)}else this.head=e,e.next=k};this.reduce=function(){for(var a=this.head;a&&a.next;){for(;a.next&&a.stop+1>=a.next.start;)a.stop<=a.next.stop&&(a.stop=a.next.stop),a.next=a.next.next;a=a.next}};this.p=function(){this.reduce();for(var a=[],b=this.head;b;)0<a.length&&
s(a,0,"_"),s(a,0,b.start),s(a,0,"_"),s(a,0,b.stop),b=b.next;return a.join("")}}var u=30,v=500,w=3,x=q,y=[],z,A,B,C,D;function E(a,b){for(var e=r.nw(),d=0;d<y.length;d++)if(y[d][1]==b)return;var d=r.ca(),g={};g[0]=a;g[3]=e;g[4]=0;g[1]=b;g[2]=d?d.name:"-";g[9]=q;s(y,0,g)}function F(a,b,e,d){for(var g=0;g<y.length;g++){var m=y[g];if(m[1]==a){2<arguments.length&&0<e&&(m[3]=e);m[4]=3<arguments.length&&0<d?d:r.nw();m[7]=b;b||(m[9]=q,m[10]=f);break}}}
function G(a,b){return a[12]<b[12]?1:a[12]==b[12]?0:-1}function H(){var a=0;r.arti&&r.arti(y);for(a=0;a<y.length;a++){var b=y[a];0===b[4]&&0<b[3]&&("i"===b[0]?(b[8]=f,b[7]=q,b[4]=r.nw()):(b[5]||(b[7]=f),b[4]=b[3]));b[12]=b[4]?b[4]-b[3]:b[12]}}
function I(){var a=r.lst();H();if(0<y.length&&0<a){var b={},e;for(e=0;e<y.length;e++){var d=y[e],g=r.gh(d[1]);b[g]||(b[g]=[]);s(b[g],0,d)}var m={},l=k;for(l in b)if(b.hasOwnProperty(l)&&b[l].length){g=b[l];g.sort(G);var h={};for(e=0;e<g.length;e++){var d=g[e],c=h[d[0]];c||(c={g:0,q:0,n:0,m:0,h:0,j:0,t:new t,v:new t,k:0,e:a+99999999,b:0,l:0,f:a+99999999,d:0},h[d[0]]=c);if(d[3]&&d[4]){c.h++;var n=d[4]-d[3];c.e=c.e<n?c.e:n;c.b=c.b>n?c.b:n;c.k=parseInt((c.k*(c.h-1)+n)/c.h,10);c.t.add(d[3]-a,d[4]-a)}d[5]&&
d[6]&&(c.j++,n=d[11],0>n&&(n=d[6]-d[5]),c.f=c.f<n?c.f:n,c.d=c.d>n?c.d:n,c.l=parseInt((c.l*(c.j-1)+n)/c.j,10),c.v.add(d[5],d[6]));c.g+=d[7]?1:0;c.m+=d[9]?1:0;d[7]||(c.q+=d[8]?1:0,c.n+=d[8]?0:1)}m[l]={u:0};for(var p in h)h.hasOwnProperty(p)&&(c=h[p],m[l].u=Math.max(c.b,c.d),m[l][p]="i"==p||"s"==p?[c.g,c.n,c.q,c.m,c.h,c.j,c.t.p(),c.k,c.h?c.e:"0",c.b,c.v.p(),c.l,c.j?c.f:"0",c.d].join("|"):"o"==p||"y"==p?[c.g,c.n,c.q,c.m,c.v.p(),c.l,c.f,c.d].join("|"):[c.g,c.t.p(),c.k,c.e,c.b].join("|"))}p=[];for(l in m)b.hasOwnProperty(l)&&
s(p,0,l);0<C&&(g=p.sort(function(a,b){return m[b].u-m[a].u}),g.length>C&&(p=g.slice(0,C)));h=[];for(c=0;c<p.length;c++){l=p[c];g=b[l];e=m[l];0<h.length&&s(h,0,";");s(h,1,r.aesc(l),"featureHash");d=0;l=h.length-2;e.i&&(s(h,1,e.i),d+=2);e.s&&(s(h,1,e.s),d+=4);e.y&&(s(h,1,e.y),d+=8);e.o&&(s(h,1,e.o),d+=16);e.c&&(s(h,1,e.c),d+=32);h.pop();h[l]=d.toString(32);for(e=0;e<g.length&&e<w&&(g[e][12]>=v||g[e][11]>=v);e++)d=g[e],s(h,0,","),s(h,0,d[0]+(d[7]?"":d[8]?"i":"f"),d[3]?d[3]-a:0,d[4]?d[4]-a:0,r.aesc(d[2]),
r.aesc(d[1])),d[5]&&s(h,0,"",d[5],d[6])}return r.esc(h.join(""))}return k}function J(a,b){if(!b&&!x){x=f;var e=I();e&&a.a("3p",e);y=[]}}function K(a){var b=r.gh(a);return!(-1!=a.indexOf("chrome-extension://")||-1!=a.indexOf("chrome://")||-1!=a.indexOf("data:"))&&(D||b&&b!=z)}function L(a){F(a.target.src,f)}function M(){window&&window.event&&window.event.srcElement&&("loaded"==window.event.srcElement.readyState||"complete"==window.event.srcElement.readyState)&&F(window.event.srcElement.src,f)}
function N(){for(var a=document.getElementsByTagName("script"),b=0;b<a.length;b++){var e=a[b];if(!e.r&&(e.r=r.nw(),""!=e.src&&K(e.src)&&(!e.attributes||!e.attributes["data-dtconfig"])))E("s",e.src),r.gBI().ie?r.ael(e,"readystatechange",M):r.ael(e,"load",L)}}function O(a){var b=k;a?a.target?b=a.target:a.srcElement&&(b=a.srcElement):window&&window.event&&(b=window.event.srcElement);b&&F(b.src,f)}
function P(a){var b=k;a?a.target?b=a.target:a.srcElement&&(b=a.srcElement):window&&window.event&&(b=window.event.srcElement);b&&b.src!=document.location.href&&F(b.src,q)}function Q(a){if(!a.r){a.r=r.nw();try{""!=a.src&&K(a.src)&&(E("i",a.src),!a.complete||"undefined"!=typeof a.naturalWidth&&0===a.naturalWidth?(r.ael(a,"load",O),r.ael(a,"error",P),a.src=a.src):F(a.src,f))}catch(b){}}}
function R(){var a=document.getElementsByTagName("img"),b,e;for(b=0;b<a.length;b++)e=a[b],Q(e);a=document.getElementsByTagName("input");for(b=0;b<a.length;b++)e=a[b],e.type&&"SUBMIT"==e.type.toUpperCase()&&Q(e)}function S(){0<A&&2E3<r.nw()-A?(B=q,r.asl(J),r.sMPS(5E3)):(R(),N(),r.st(S,u))}var T=r.cfg("tp")?r.cfg("tp"):"500,50,3";
if(r.smbi("3")){var U=T.split(","),V=U.length;3<=V&&5>=V&&(v=parseInt(U[0],10),u=parseInt(U[1],10),w=parseInt(U[2],10),4<=V&&(D=parseInt(U[3],10)),5==V&&(C=parseInt(U[4],10)),z=r.gh(document.location.href),r.apll(function(){r.asl(J)}),r.all(function(){A=r.nw()}),r.asl(function(){-1===A&&(A=r.nw())}),r.tpstr=E,r.tpsto=F,r.tpih=K,R(),N(),r.ca()&&!B&&(A=r.nw(),B=f,S()),A=-1)};
})();